export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const GET_ALL_ACTIVITIES = 'GET_ALL_ACTIVITIES';
export const GET_ALL_PRECIOS = 'GET_ALL_PRECIOS';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_ALL_COMMENTS = 'GET_ALL_COMMENTS'
